### ISSUE TITLE
Linux/Windows test logs filled - No property tester contributes a property org.eclipse.debug.ui.matchesContentType to type  

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-tools-eclipse#242]
Not sure why this doesn't happen yet for me locally, but the test logs are filled with the messages below.

I seem to find a lot of search hits online overlapping similar problems in various plugins.

> 2022-11-14T03:00:46.2195300Z !ENTRY org.eclipse.debug.ui 4 0 2022-11-14 03:00:45.410
> 2022-11-14T03:00:46.2205945Z !MESSAGE Launch shortcut 'org.eclipse.ant.ui.antShortcutWithDialog' enablement expression caused exception. Shortcut was removed.
> 2022-11-14T03:00:46.2206424Z !STACK 1
> 2022-11-14T03:00:46.2208095Z org.eclipse.core.runtime.CoreException: No property tester contributes a property org.eclipse.debug.ui.matchesContentType to type class java.lang.String
> 2022-11-14T03:00:46.2323774Z 	at org.eclipse.core.internal.expressions.TypeExtensionManager.getProperty(TypeExtensionManager.java:131)
> 2022-11-14T03:00:46.2324492Z 	at org.eclipse.core.expressions.TestExpression.evaluate(TestExpression.java:104)
> 2022-11-14T03:00:46.2325101Z 	at org.eclipse.core.expressions.CompositeExpression.evaluateOr(CompositeExpression.java:68)
> 2022-11-14T03:00:46.2325681Z 	at org.eclipse.core.expressions.OrExpression.evaluate(OrExpression.java:26)
> 2022-11-14T03:00:46.2326273Z 	at org.eclipse.core.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:54)
> 2022-11-14T03:00:46.2327053Z 	at org.eclipse.core.internal.expressions.IterateExpression.evaluate(IterateExpression.java:163)
> 2022-11-14T03:00:46.2327901Z 	at org.eclipse.core.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:54)
> 2022-11-14T03:00:46.2329273Z 	at org.eclipse.core.expressions.WithExpression.evaluate(WithExpression.java:84)
> 2022-11-14T03:00:46.2329864Z 	at org.eclipse.core.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:54)
> 2022-11-14T03:00:46.2331613Z 	at org.eclipse.core.internal.expressions.EnablementExpression.evaluate(EnablementExpression.java:59)
> 2022-11-14T03:00:46.2333438Z 	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension.evalEnablementExpression(LaunchShortcutExtension.java:280)
> 2022-11-14T03:00:46.2344281Z 	at org.eclipse.debug.ui.actions.LaunchShortcutsAction.isApplicable(LaunchShortcutsAction.java:264)
> 2022-11-14T03:00:46.2344932Z 	at org.eclipse.debug.ui.actions.LaunchShortcutsAction.fillMenu(LaunchShortcutsAction.java:173)
> 2022-11-14T03:00:46.2345572Z 	at org.eclipse.debug.ui.actions.LaunchShortcutsAction$2.menuShown(LaunchShortcutsAction.java:281)
> 2022-11-14T03:00:46.2346163Z 	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:259)
> 2022-11-14T03:00:46.2346693Z 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 2022-11-14T03:00:46.2347133Z 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
> 2022-11-14T03:00:46.2347810Z 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
> 2022-11-14T03:00:46.2348300Z 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
> 2022-11-14T03:00:46.2349203Z 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
> 2022-11-14T03:00:46.2349728Z 	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
> 2022-11-14T03:00:46.2350354Z 	at org.eclipse.jface.action.ActionContributionItem.copyMenu(ActionContributionItem.java:1191)
> 2022-11-14T03:00:46.2351094Z 	at org.eclipse.jface.action.ActionContributionItem.handleShowProxy(ActionContributionItem.java:1171)
> 2022-11-14T03:00:46.2352000Z 	at org.eclipse.jface.action.ActionContributionItem.lambda$7(ActionContributionItem.java:1134)
> 2022-11-14T03:00:46.2352580Z 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 2022-11-14T03:00:46.2353241Z 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
> 2022-11-14T03:00:46.2353658Z 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
> 2022-11-14T03:00:46.2354118Z 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
> 2022-11-14T03:00:46.2354820Z 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
> 2022-11-14T03:00:46.2355245Z 	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
> 2022-11-14T03:00:46.2355832Z 	at org.eclipse.swtbot.swt.finder.finders.MenuFinder.findMenuItemInternal(MenuFinder.java:218)
> 2022-11-14T03:00:46.2356500Z 	at org.eclipse.swtbot.swt.finder.finders.MenuFinder.findMenuItemInternal(MenuFinder.java:219)
> 2022-11-14T03:00:46.2357164Z 	at org.eclipse.swtbot.swt.finder.finders.MenuFinder.findMenuItemInternal(MenuFinder.java:219)
> 2022-11-14T03:00:46.2357728Z 	at org.eclipse.swtbot.swt.finder.finders.MenuFinder.access$0(MenuFinder.java:194)
> 2022-11-14T03:00:46.2358472Z 	at org.eclipse.swtbot.swt.finder.finders.MenuFinder$2.run(MenuFinder.java:148)
> 2022-11-14T03:00:46.2359178Z 	at org.eclipse.swtbot.swt.finder.finders.MenuFinder$2.run(MenuFinder.java:1)
> 2022-11-14T03:00:46.2360167Z 	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$2.doRun(UIThreadRunnable.java:142)
> 2022-11-14T03:00:46.2360765Z 	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable.run(UIThreadRunnable.java:78)
> 2022-11-14T03:00:46.2361546Z 	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable.syncExec(UIThreadRunnable.java:144)
> 2022-11-14T03:00:46.2362423Z 	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable.syncExec(UIThreadRunnable.java:126)
> 2022-11-14T03:00:46.2362999Z 	at org.eclipse.swtbot.swt.finder.finders.MenuFinder.findMenuItem(MenuFinder.java:145)
> 2022-11-14T03:00:46.2363580Z 	at org.eclipse.swtbot.swt.finder.waits.WaitForMenuItem$1.run(WaitForMenuItem.java:84)
> 2022-11-14T03:00:46.2364144Z 	at org.eclipse.swtbot.swt.finder.waits.WaitForMenuItem$1.run(WaitForMenuItem.java:1)
> 2022-11-14T03:00:46.2364736Z 	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$2.doRun(UIThreadRunnable.java:142)
> 2022-11-14T03:00:46.2365437Z 	at org.eclipse.swtbot.swt.finder.finders.UIThreadRunnable$1.run(UIThreadRunnable.java:90)
> 2022-11-14T03:00:46.2366055Z 	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
> 2022-11-14T03:00:46.2368151Z 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
> 2022-11-14T03:00:46.2368743Z 	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4043)
> 2022-11-14T03:00:46.2369318Z 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3648)
> 2022-11-14T03:00:46.2369977Z 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
> 2022-11-14T03:00:46.2370663Z 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 2022-11-14T03:00:46.2371308Z 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
> 2022-11-14T03:00:46.2372016Z 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 2022-11-14T03:00:46.2372612Z 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
> 2022-11-14T03:00:46.2373527Z 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 2022-11-14T03:00:46.2374177Z 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
> 2022-11-14T03:00:46.2374830Z 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
> 2022-11-14T03:00:46.2375486Z 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
> 2022-11-14T03:00:46.2376337Z 	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:29)
> 2022-11-14T03:00:46.2377062Z 	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:122)
> 2022-11-14T03:00:46.2377747Z 	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:35)
> 2022-11-14T03:00:46.2378312Z 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 2022-11-14T03:00:46.2378989Z 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
> 2022-11-14T03:00:46.2380252Z 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
> 2022-11-14T03:00:46.2381295Z 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
> 2022-11-14T03:00:46.2381805Z 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 2022-11-14T03:00:46.2382362Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 2022-11-14T03:00:46.2382975Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 2022-11-14T03:00:46.2383802Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 2022-11-14T03:00:46.2384300Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 2022-11-14T03:00:46.2384945Z 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
> 2022-11-14T03:00:46.2385430Z 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
> 2022-11-14T03:00:46.2385834Z 	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
> 2022-11-14T03:00:46.2386276Z 	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
> 2022-11-14T03:00:46.2387175Z !SUBENTRY 1 org.eclipse.core.expressions 4 201 2022-11-14 03:00:45.410

**Comment by scottkurz** [comment]
Doesn't seem like it needs to be a priority for this milestone.
