### ISSUE TITLE
Installing Liberty Tools 0.8.0 breaks Chain Template Proposals for this example

### ISSUE THREAD

**Issue by erik-brangs** [OpenLiberty/liberty-tools-eclipse#334]
I installed Open Liberty Tools 0.8.0 today to try out lsp4jakarta . I'm using Eclipse 2022-12 for Web Developers.

I have enabled "Chain Template Proposals" under Preferences -> Java -> Editor -> Content Assist -> Advanced.

The computation of proposals fails for some code as described below. The failure leads to an annoying popup ("Problems During Content Assist").

The following source files reproduce the problem:

```
public class Example {
	
	public Example() {
	}

}
```

```
class ExampleTest {
	
	void test() {
		Example example = new Example();
	}
	
}
```

When placing the caret in the brackets in second file in the line with the constructor, i.e. ``Example example = new Example(^);`` and pressing Ctrl+Space, the computation of proposals fails.

Error Log - Event Details - Message
```
The 'org.eclipse.jdt.ui.org.eclipse.jdt.ui.javaCompletionProposalComputer.chain' proposal computer from the 'org.eclipse.jdt.ui' plug-in did not complete normally. The extension has thrown a runtime exception.
```

Error Log - Event Details - Exception Stack Trace
```
java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at org.eclipse.jdt.internal.ui.text.java.ChainCompletionProposalComputer.executeCallChainSearch(ChainCompletionProposalComputer.java:155)
	at org.eclipse.jdt.internal.ui.text.java.ChainCompletionProposalComputer.computeCompletionProposals(ChainCompletionProposalComputer.java:77)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:348)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:340)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:333)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:289)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$10(AsyncCompletionProposalPopup.java:378)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$9(AsyncCompletionProposalPopup.java:377)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by scottkurz** [comment]
Thank you for reporting.  I recreated the issue the first time based on this description.

**Comment by scottkurz** [comment]
Looking at this a bit in the debugger, it does make me wonder about the fact that we have a back-level JDT LS bundle.   We have that issue tracked here:  https://github.com/OpenLiberty/liberty-tools-eclipse/issues/243.

It's just a guess so I don't want to overstate the analysis here, but there have been JDT LS changes like this  https://github.com/eclipse/eclipse.jdt.ls/issues/2272 at least affecting the preferences that we're failing to read in the stack trace in this problem. 

I would like to take a look at resolving https://github.com/OpenLiberty/liberty-tools-eclipse/issues/243 as we look at integrating with Eclipse v4.27 (1Q23) and then come back to this particular problem.

**Comment by scottkurz** [comment]
Tried on Eclipse v4.27 with org.eclipse.jdt.ls.core 1.22 and the same problem still exists.  

The JDT LS code isn't even on the exception stack trace, so that might have been too much wishful thinking before.   

Will have to look at this in more detail.

**Comment by scottkurz** [comment]
This is fixed.  I verified with Liberty Tools Eclipse v23.0.9

**Comment by erik-brangs** [comment]
Thank you. I can confirm that the problem is fixed with the current version on Eclipse 2023-09.
