### ISSUE TITLE
Automated tests fail with WidgetNotFoundException for no apparent reason

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-tools-eclipse#350]
## DETAILS

I've seen this both locally (on my laptop) and in GHA.

Here's a log from a GHA running for PR  #330 
[1_Build Plugin (linux, 3Q2022).zip](https://github.com/OpenLiberty/liberty-tools-eclipse/files/11029106/1_Build.Plugin.linux.3Q2022.zip)

With nothing obviously wrong beforehand, we see:
```text
2023-03-19T19:47:45.3471273Z io.openliberty.tools.eclipse.test.it.LibertyPluginSWTBotGradleTest.testStartWithCustomDebugAsConfig  Time elapsed: 96.364 s  <<< ERROR!
2023-03-19T19:47:45.3472388Z org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find menu bar for shell: Shell with text {Debug Configurations}
2023-03-19T19:47:45.3473487Z 	at io.openliberty.tools.eclipse.test.it.LibertyPluginSWTBotGradleTest.testStartWithCustomDebugAsConfig(LibertyPluginSWTBotGradleTest.java:564)
2023-03-19T19:47:45.3474644Z Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 20000 ms.: Could not find menu bar for shell: Shell with text {Debug Configurations}
2023-03-19T19:47:45.3475903Z 	at io.openliberty.tools.eclipse.test.it.LibertyPluginSWTBotGradleTest.testStartWithCustomDebugAsConfig(LibertyPluginSWTBotGradleTest.java:564)
2023-03-19T19:47:45.3476663Z 
```

### NOTES FROM DEBUG SESSION

I did recreate in a local session in the debugger and notice some things of interest.

When the test failed, the last method within our codebase on the stack was:

```java
    public static void switchToProjectExplorerView(SWTWorkbenchBot bot) {

        String projExpViewName = "Project Explorer";
        bot.menu("Window").menu("Show View").menu(projExpViewName).click();
        int maxRetries = 10;
        String activeViewTitle = null;

        for (int i = 0; i < maxRetries; i++) {
            SWTBotView activeView = bot.activeView();
            activeViewTitle = activeView.getTitle();

            if (projExpViewName.equals(activeViewTitle)) {
                try {
                    bot.waitUntil(SWTBotTestCondition.isViewActive(activeView, activeView.getTitle()), 10000)
```

So the failure was in the last line, the `SWTBotTestCondition.isViewActive()`  method.

Now, I could see looking at the child Eclipse that the Proj. Explorer view did indeed appear to be active.

Debugging in, I seemed to find a root cause of the failure in method:
**org.eclipse.swtbot.swt.finder.finders.ControlFinder.findControlsInternal(Widget, Matcher<T>, boolean)**

In this code:

```java
	@SuppressWarnings("unchecked")
	private <T extends Widget> List<T> findControlsInternal(final Widget parentWidget, final Matcher<T> matcher, final boolean recursive) {
		if ((parentWidget == null) || parentWidget.isDisposed())
			return new ArrayList<T>();
```

it seemed the parentWidget was 'null', which seemed to surface back up as the WidgetNotFoundException noticed, as before.

**CAVEAT:** I'm not sure I didn't subtly alter something by controlling things in the debugger.  Would need to more carefully recreate.

## NOTE

Until we fix this we are stuck just rerunning our GHA tests every time we hit an issue like this, hoping it doesn't reoccur.  Obviously this is bad, but I don't think at this point there are true issues with our Liberty Tools Eclipse code.

**Comment by scottkurz** [comment]
Fixed by https://github.com/OpenLiberty/liberty-tools-eclipse/pull/367  (I hope)
