### ISSUE TITLE
Intermittent test failure in LibertyPluginSWTBotMavenTest.setup()

### ISSUE THREAD

**Issue by awisniew90** [OpenLiberty/liberty-tools-eclipse#375]
-------------------------------------------------------------------------------
Test set: io.openliberty.tools.eclipse.test.it.LibertyPluginSWTBotMavenTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 73.966 s <<< FAILURE! - in null
io.openliberty.tools.eclipse.test.it.LibertyPluginSWTBotMavenTest  Time elapsed: 73.966 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: The runAs menu associated with project: liberty.maven.test.app does not contain one or more expected entries. Expected number of entries: 7Found entry count: 5. Found menu entries: [1 Liberty Start, 2 Liberty Start in Container, 3 Liberty Start..., 4 Liberty Stop, 5 Liberty Run Tests, , Run Configurations...] ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:211)
	at io.openliberty.tools.eclipse.test.it.LibertyPluginSWTBotMavenTest.validateBeforeTestRun(LibertyPluginSWTBotMavenTest.java:213)
	at io.openliberty.tools.eclipse.test.it.LibertyPluginSWTBotMavenTest.setup(LibertyPluginSWTBotMavenTest.java:144)

**Comment by scottkurz** [comment]
I suspect that the Maven project nature hasn't been added or reloaded by the time the Run As menu is constructed.

It's notable that, from the assertion failure output, the missing menu entries are the view test report entries.  These entries have an extra enablement check in the **plugin.xml**, e.g. they have:

```xml
      <shortcut
          class="io.openliberty.tools.eclipse.ui.launch.shortcuts.OpenMavenITestReportAction"
...
                              <test forcePluginActivation="true" property="org.eclipse.debug.ui.projectNature" value="io.openliberty.tools.eclipse.ui.libertyNature"/>
                              <test forcePluginActivation="true" property="org.eclipse.debug.ui.projectNature" value="org.eclipse.m2e.core.maven2Nature"/>
```
whereas the others, the five that do show up, don't have the extra enablement check for Maven nature, only for Liberty nature.  This allows us to have different options for Maven vs Gradle app projects.

Some ideas:
* Just wait longer, in general, after the tests app are imported (GHA is waiting 60s today)
* If we do fail this validation, also dump the .project file to confirm this is the problem.   Note this may not be all that helpful, if there's any lag between updating that .project file on disk and loading it to the place where this project nature test is performed... (not saying there is actually such a lag just that we don't know for sure there isn't).
* Create a .project file in the test app source for each test project which already has the Maven/Gradle nature.  (Presumably that would fix things if there's a delay in updating).
