### ISSUE TITLE
Failure in LibertyPluginSWTBotGradleTest.testDashboardDebugWithCustomConfigAction - widget not found

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/liberty-tools-eclipse#433]
> 2023-09-08T19:44:40.2947775Z java.lang.RuntimeException: Unable to locate widget: Start parameters:
> 2023-09-08T19:44:40.2948419Z 	at io.openliberty.tools.eclipse.test.it.utils.MagicWidgetFinder.find(MagicWidgetFinder.java:1054)
> 2023-09-08T19:44:40.2949294Z 	at io.openliberty.tools.eclipse.test.it.utils.SWTBotPluginOperations.setCustomStartParmsFromShell(SWTBotPluginOperations.java:541)
> 2023-09-08T19:44:40.2950363Z 	at io.openliberty.tools.eclipse.test.it.utils.SWTBotPluginOperations.launchCustomDebugFromDashboard(SWTBotPluginOperations.java:523)
> 2023-09-08T19:44:40.2951532Z 	at io.openliberty.tools.eclipse.test.it.LibertyPluginSWTBotGradleTest.testDashboardDebugWithCustomConfigAction(LibertyPluginSWTBotGradleTest.java:428)
> 

This failure was introduced by an earlier version of https://github.com/OpenLiberty/liberty-tools-eclipse/pull/428.  It seemed to occur consistently on Linux in particular.

We decided to workaround the failure by configuring the tests to run in alphabetical order.   Our guess is that the way to understand this fact is that the error is provoked by runningthe LibertyPluginSWTBotMavenTest tests before the LibertyPluginSWTBotGradleTest tests, and worked around when these are run in the opposite relative order, such that the Gradle tests are run first (it's conceivable there are other complicating factors, including possibly the other test classes).

Opening this issue to follow up on the failure, to understand it better.  This will hopefully help us more generally under these SWTBot tests.   It's not that running the tests in a predictable alphabetical order is necessarily bad, but we'd like to understand the failure while it's happening consistently, (as it was when merging the PR on top of the HEAD of https://github.com/OpenLiberty/liberty-tools-eclipse/commit/2fb4b6b2f3a87599c60e4571220eb593e5dd3cbe).

**Comment by awisniew90** [comment]
I may have gotten to the same conclusion (aeonbits bundle issue) but from a different angle... 

There are two main dependencies that are needed from the com.automation-remarks video recorder libraries:

1. video-recorder-junit5
2. video-recorder-core (used by junit5^)

These dependencies can be added to the target platform file like so:

`<location includeDependencyDepth="none" includeDependencyScopes="compile" missingManifest="generate" type="Maven">
		    <dependencies>
			    <dependency>
				    <groupId>com.automation-remarks</groupId>
				    <artifactId>video-recorder-junit5</artifactId>
				    <version>2.0</version>
				    <type>jar</type>
			    </dependency>
		    </dependencies>
	    </location>`

and tycho will generate a manifest for them and bundle them into bundles with the prefix "wrapped" added. e.g. "wrapped.com.automation-remarks.video-recorder-junit5"

In trying to recreate Scott's issue with aeobits bundling, I first simplified things and tried to bundle these two dependencies separately. Each had "none" specified in the target platform file for "dependency depth" which means "dont try to bundle any direct or transitive dependencies". I found that the dialog window in Eclipse for the target-platform file was showing an error that video-recorder-core could not be bundles, but this seems benign as the logs for a maven install are showing the bundle being generated. However, the junit5 bundle could only find classes in the core bundle if the core bundle (with "wrapped" prefix) was added as a "Required-Bundle" in our test projects Manifest file. 

The latest issue is that the core bundle cannot find a class in the aeonbits dependency library:

`Caused by: java.lang.ClassNotFoundException: org.aeonbits.owner.ConfigFactory cannot be found by wrapped.com.automation-remarks.video-recorder-core_2.0.0`

I then added the com.aeonbits.owner dependency to the target platform, but the bundle does not seem to be generated and no manifest is created as is done for the other dependencies. e.g. for video-recorder-junit5:

`[INFO] com.automation-remarks:video-recorder-junit5:2.0 is wrapped as a bundle with bundle symbolic name wrapped.com.automation-remarks.video-recorder-junit5
[INFO] The artifact can be referenced in feature files with the following data: <plugin id="wrapped.com.automation-remarks.video-recorder-junit5" version=" 2.0" download-size="0" install-size="0" unpack="false"/>
[DEBUG] The following manifest was generated for this artifact:
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Created-By: 17.0.6 (IBM Corporation)
Tool: Bnd-6.3.1.202206071316
Bnd-LastModified: 1707155912321
Export-Package: com.automation.remarks.junit5;version=" 2.0";uses:="com.
 automation.remarks.video.annotations,org.junit.jupiter.api.extension"
Import-Package: com.automation.remarks.video;resolution:=optional,com.au
 tomation.remarks.video.annotations;resolution:=optional,com.automation.
 remarks.video.enums;resolution:=optional,com.automation.remarks.video.r
 ecorder;resolution:=optional,org.junit.jupiter.api.extension;resolution
 :=optional,org.junit.platform.commons.util;resolution:=optional
DynamicImport-Package: *
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Bundle-Name: Bundle derived from maven artifact com.automation-remarks:v
 ideo-recorder-junit5:2.0
Bundle-Version:  2.0
Bundle-SymbolicName: wrapped.com.automation-remarks.video-recorder-junit
 5`
 
 I have yet to debug why the aeobits dependency is not being bundled. no obvious errors are shown.  This could perhaps be the same issue Scott saw, but given that this is not bundling two dependencies together it seems it may be a different issue. getting past could potentially make this work. 

Changes are here: https://github.com/awisniew90/liberty-tools-eclipse/tree/video-recorder
